language: python
python:
  - "2.7"
env:
  before_install:
    - sudo apt-get update -qq
    - sudo apt-get upgrade -qq
branches:
  only:
    - master
script: ./run_tests.sh -V
notifications:
  email:
    recipients:
      - mauro@kili.io
      - james@kili.io
      - adam@kili.io
    on_success: change
    on_failure: change
